.TH "GEOBLAZE" "1" "January 2019" "" "GeoBlaze CLI"
.SH "NAME"
\fBgeoblaze\fR - a command line interface for blazing fast raster analysis
.SH "SYNOPSIS"
.RS 0
.IP \(bu 4
\fBgeoblaze help\fR
.IP \(bu 4
\fBgeoblaze identify <georaster> <point>\fR
.IP \(bu 4
\fBgeoblaze id <georaster> <point>\fR
.IP \(bu 4
\fBgeoblaze bandArithmetic <georaster> <expression>\fR
.IP \(bu 4
\fBgeoblaze histogram <georaster> \[lB]geovector\[rB] \[lB]--scaleType={nominal|ratio}\[rB] \[lB]--numClasses=<numClasses>\[rB] \[lB]--classType={equal-interal|quantile}\[rB]\fR
.IP \(bu 4
\fBgeoblaze max <georaster> \[lB]geovector\[rB]\fR
.IP \(bu 4
\fBgeoblaze min <georaster> \[lB]geovector\[rB]\fR
.IP \(bu 4
\fBgeoblaze mean <georaster> \[lB]geovector\[rB]\fR
.IP \(bu 4
\fBgeoblaze median <georaster> \[lB]geovector\[rB]\fR
.IP \(bu 4
\fBgeoblaze mode <georaster> \[lB]geovector\[rB]\fR
.IP \(bu 4
\fBgeoblaze rasterCalculator <georaster> <functionBody>\fR
.IP \(bu 4
\fBgeoblaze calc <georaster> \[lB]geovector\[rB] <functionBody>\fR
.IP \(bu 4
\fBgeoblaze sum <georaster> \[lB]geovector\[rB]\fR
.IP \(bu 4
\fBgeoblaze version\fR
.RE 0

.SH "DESCRIPTION"
.P
GeoBlaze CLI is an open-source command line interface to the GeoBlaze JavaScript Raster Processing Engine (geoblaze.io). It allows you to do simple basic aggregate statistics like, mean, median and mode while only typing one line. You can also use it to simply run band arithmetic like NDVI and save the result to a file.
.SH "OPTIONS"
.RS 0
.IP \(bu 4
\fBhelp\fR: Display this helpful information
.IP \(bu 4
\fBidentify\fR, \fBid\fR: Get the value of the pixel at the specified point. The Point should be specified as a longitude and latitude pair "-40,20"
.IP \(bu 4
\fBbandArithmetic\fR: Run band arithmetic, like NDVI, on a raster and save the result to a file.
.IP \(bu 4
\fBhistogram\fR: Calculate the histogram of a raster.
.IP \(bu 4
\fBmax\fR: Get the highest value in the raster, ignoring no data values.
.IP \(bu 4
\fBmin\fR: Get the lowest value in the raster, ignoring no data values.
.IP \(bu 4
\fBmean\fR: Get the mean average of pixel values in a raster. You can optionally specify a geovector file, like a geojson or a shapefile, so the calculation is only run on the pixels of the raster inside of the vectors.
.IP \(bu 4
\fBmedian\fR: Get the median average of pixel values in a raster. You can optionally specify a geovector file, like a geojson or a shapefile, so the calculation is only run on the pixels of the raster inside of the vectors.
.IP \(bu 4
\fBmode\fR: Get the most common pixel value in a raster. You can optionally specify a geovector file, like a geojson or a shapefile, so the calculation is only run on the pixels of the raster inside of the vectors.
.IP \(bu 4
\fBrasterCalculator\fR, \fBcalc\fR: Run a function on the specified raster file and save the new raster to a file.
.IP \(bu 4
\fBsum\fR: Get the sum of pixel values in a raster file. You can optionally specify a geovector file, like a geojson or a shapefile, so the calculation is only run on the pixels of the raster inside of the vectors.
.IP \(bu 4
\fBversion\fR: Show version, which is found in the package.json
.RE 0

.SH "EXAMPLES"
.SS "Get the Pixel Value at Paris, France"
.P
\fBgeoblaze id image.tiff "48.8567,2.3508"\fR
.SS "Get Acreage of Wheat in Ukraine"
.P
\fBgeoblaze sum wheat.tiff ukraine.geojson\fR
.SS "Calculate NDVI"
.P
\fBgeoblaze bandArithmetic image.tiff '(c - b)/(c + b)'\fR
.SS "Binarize a Raster"
.P
\fBgeoblaze rasterCalculator image.tiff 'return A > 100 ? 1 : 0'\fR
.SS "More Examples"
.P
 \fI\(lahttps://github.com/GeoTIFF/geoblaze-cli/blob/master/EXAMPLES.md\(ra\fR
.SH "AUTHOR"
.P
 Daniel J. Dufour: \fI\(lahttps://danieljdufour.com\(ra\fR
.SH "BUGS"
.RS 0
.IP \(bu 4
\fI\(lahttps://github.com/GeoTIFF/geoblaze-cli/issues/\(ra\fR
.RE 0

.SH "INTERNET RESOURCES"
.RS 0
.IP \(bu 4
Source Code Repository: \fI\(lahttps://github.com/GeoTIFF/geoblaze-cli\(ra\fR
.IP \(bu 4
Package Manager Entry: \fI\(lahttps://www.npmjs.com/package/geoblaze-cli\(ra\fR
.IP \(bu 4
Slack Channel: \fI\(lahttps://geotiff.slack.com\(ra\fR
.IP \(bu 4
Issue Tracker: \fI\(lahttps://github.com/GeoTIFF/geoblaze-cli/issues\(ra\fR
.IP \(bu 4
GeoBlaze Information: \fI\(lahttps://geoblaze.io\(ra\fR
.IP \(bu 4
Intersection Algorithm: \fI\(lahttps://medium.com/@DanielJDufour/calculating-intersection-of-polygon-with-a-raster-89c2624d78a2\(ra\fR
.RE 0

.SH "LICENSING"
.P
 The GeoBlaze CLI is distributed under the MIT License. See the file \fB"LICENSE"\fR \fI\(laLICENSE\(ra\fR in the GeoBlaze CLI source-distribution for information on terms & conditions for accessing and otherwise using the GeoBlaze CLI and for a DISCLAIMER OF ALL WARRANTIES.
